name: Automatic tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mfinelli/setup-imagemagick@v5
        with:
          cache: true
      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: just
      - uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.13.0
      - run: |
          just test
