name: Update Tests images
on:
  workflow_dispatch:

jobs:
  update-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: imagemagick cargo
          version: 1.0
      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: just
      - uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.12.0
      - run: |
          typst fonts
      - run: |
          just update-test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: |
            tests
